### ISSUE TITLE
FunctionClauseError is raised when sobelow encounters a JSON file in the root directory

### ISSUE THREAD

**Issue by supernova32** [nccgroup/sobelow#16]
While trying to scan my Phoenix project, sobelow crashes almost immediately after trying to parse a JSON file in the root directory of my project. Here is the trace:

```
** (FunctionClauseError) no function clause matching in Sobelow.Utils.extract_opts/1
    lib/sobelow/utils.ex:348: Sobelow.Utils.extract_opts(".alloy-ci.json")
    lib/sobelow/utils.ex:436: Sobelow.Utils.get_pipe_val/3
    (elixir) lib/macro.ex:296: anonymous fn/4 in Macro.do_traverse_args/4
    (elixir) lib/enum.ex:1325: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
    (elixir) lib/macro.ex:262: Macro.do_traverse/4

    (elixir) lib/enum.ex:1325: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
    (elixir) lib/enum.ex:1325: Enum."-map_reduce/3-lists^mapfoldl/2-
```

I'm running sobelow v0.3.11 installed from hex.

**Comment by GriffinMB** [comment]
If you re-install, it should work now! Let me know and thanks for the report.

**Comment by supernova32** [comment]
Awesome! It works fine now, thanks for the quick turnaround 👍
