### ISSUE TITLE
Preferred CSP Header Causes Test Failure

### ISSUE THREAD

**Issue by jherdman** [nccgroup/sobelow#49]
Using the example good router as an example and a freshly generated Phoenix app, the following error occurs:

```
  1) test GET / (MyApp.PageControllerTest)
     test/my_app/controllers/page_controller_test.exs:4
     ** (Plug.Conn.InvalidHeaderError) header key is not lowercase: "Content-Security-Policy"
     code: conn = get(conn, "/")
     stacktrace:
       (plug) lib/plug/conn.ex:1604: Plug.Conn.validate_header_key_if_test!/2
       (plug) lib/plug/conn.ex:853: anonymous fn/3 in Plug.Conn.merge_resp_headers/2
       (stdlib) maps.erl:232: :maps.fold_1/3
       (plug) lib/plug/conn.ex:851: Plug.Conn.merge_resp_headers/2
       (my_app) MyApp.Router.browser/2
       (my_app) lib/my_app/router.ex:1: MhApp.Router.__pipe_through0__/1
       (phoenix) lib/phoenix/router.ex:283: Phoenix.Router.__call__/2
       (my_app) lib/my_app/endpoint.ex:1: MyApp.Endpoint.plug_builder_call/2
       (my_app) lib/my_app/endpoint.ex:1: MyApp.Endpoint.call/2
       (phoenix) lib/phoenix/test/conn_test.ex:235: Phoenix.ConnTest.dispatch/5
       test/my_app/controllers/page_controller_test.exs:5: (test)
```

**Comment by GriffinMB** [comment]
Thanks for opening this issue! Plug expects normalized header keys since headers are case-insensitive. Sobelow should appropriately validate the normalized header value, so using "content-security-policy" (all lowercase) should satisfy both Plug and Sobelow. It certainly makes sense to follow best-practices in examples though, so I've updated the [tests](https://github.com/nccgroup/sobelow/blob/master/test/fixtures/csp/good_router.ex#L4) accordingly.
