### ISSUE TITLE
`--exit` option doesn’t work when there are no errors

### ISSUE THREAD

**Issue by lleger** [nccgroup/sobelow#8]
I have a project that passes Sobelow with no warnings:

```bash
$ mix sobelow
##############################################
#                                            #
#          Running Sobelow - v0.3.6          #
#  Created by Griffin Byatt - @griffinbyatt  #
#     NCC Group - https://nccgroup.trust     #
#                                            #
##############################################

... SCAN COMPLETE …
$ echo $? # 0
```

If I pass the `--exit` option, it gives me a failure and a 0 exit status:

```bash
$ mix sobelow --exit Low
##############################################
#                                            #
#          Running Sobelow - v0.3.6          #
#  Created by Griffin Byatt - @griffinbyatt  #
#     NCC Group - https://nccgroup.trust     #
#                                            #
##############################################

... SCAN COMPLETE ...
** (FunctionClauseError) no function clause matching in System.halt/1
    (elixir) lib/system.ex:466: System.halt(nil)
    (mix) lib/mix/task.ex:294: Mix.Task.run_task/3
    (mix) lib/mix/cli.ex:58: Mix.CLI.run_task/2
    (elixir) lib/code.ex:370: Code.require_file/2
$ echo $? # 1
```

I would expect this to not error and exit with 0.

**Comment by kerryb** [comment]
I just came across exactly the same issue (let me guess – you arrived here via Elixir Radar). I think I've spotted the problem – I'll try to put together a quick PR.

**Comment by GriffinMB** [comment]
Thanks for the report! I just pushed an update with a couple bug fixes, this one included. Let me know if this works for you.

@kerryb Thank you for the PR. Sorry I fixed it before seeing your note!

**Comment by kerryb** [comment]
Yes, new version seems to work. Thanks :-)

**Comment by lleger** [comment]
Wow, fast response. Confirmed new version works, thanks! 👍
